name: Package Application with Pyinstaller

on:
  push:
    paths:
      - '*.py'

  workflow_dispatch:

jobs:
  build:

    runs-on: windows-2019

    steps:
    - name: Set up build environment
      uses: actions/checkout@v2
      
    - run: python -m pip install pyinstaller requests

    - name: Package app  
      run: pyinstaller -F vrcfav.py
    
    - name: Upload release
      uses: Xotl/cool-github-releases@16c58a5863d6ba9944f63ca8bb78bb3249ce1d81
      with:
        mode: update
        isPrerelease: false
        tag_name: continous
        release_name: "Automatic CI builds"
        assets: dist/vrcfav.exe
        replace_assets: true
        body_mrkdwn: |
          _This is the newest build, but Github date can't be updated. Corresponding commit: ${{ github.sha }}_
        github_token: ${{ github.token }}
